export const SUPER_ADMIN_EMAIL = 'diegoloor124@gmail.com';

export const MOCK_PROPERTIES = [
  {
    id: 'mock-1',
    title: 'Penthouse con vista al río Guayas',
    price: 385_000,
    location: 'Urdesa, Guayaquil',
    beds: 3,
    baths: 3,
    sqft: 210,
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
    status: 'Disponible',
    description: 'Ático exclusivo con vistas al río, acabados de alta gama y terraza privada. Zona residencial premium de Guayaquil.',
  },
  {
    id: 'mock-2',
    title: 'Villa contemporánea en valle de Cumbayá',
    price: 520_000,
    location: 'Cumbayá, Quito',
    beds: 5,
    baths: 6,
    sqft: 420,
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
    status: 'En venta',
    description: 'Villa de diseño minimalista con jardín, domótica completa y zona de parrilla. Uno de los sectores más exclusivos de Quito.',
  },
  {
    id: 'mock-3',
    title: 'Departamento loft en edificio patrimonial',
    price: 185_000,
    location: 'Centro Histórico, Cuenca',
    beds: 2,
    baths: 2,
    sqft: 140,
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
    status: 'Disponible',
    description: 'Loft de techos altos en edificio restaurado, a pasos de plazas y museos. Ideal para inversión o residencia en Cuenca.',
  },
  {
    id: 'mock-4',
    title: 'Casa de playa con piscina en Manta',
    price: 298_000,
    location: 'Tarqui, Manta',
    beds: 4,
    baths: 4,
    sqft: 320,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    status: 'Disponible',
    description: 'Casa a metros del mar con piscina, jardín y terraza. Zona residencial tranquila en Manta.',
  },
  {
    id: 'mock-5',
    title: 'Apartamento premium en torre de Guayaquil',
    price: 245_000,
    location: 'Samborondón, Guayaquil',
    beds: 3,
    baths: 2,
    sqft: 195,
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
    status: 'En venta',
    description: 'Apartamento en torre con amenities: gimnasio, piscina y seguridad 24h. Samborondón, Guayaquil.',
  },
  {
    id: 'mock-6',
    title: 'Casa campestre en valle de Los Chillos',
    price: 410_000,
    location: 'Valle de Los Chillos, Quito',
    beds: 5,
    baths: 4,
    sqft: 380,
    image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80',
    status: 'Disponible',
    description: 'Casa con jardín amplio, zona de parrilla y clima templado. Ideal para familia en los valles de Quito.',
  },
  {
    id: 'mock-7',
    title: 'Departamento frente al malecón de Manta',
    price: 165_000,
    location: 'Malecón, Manta',
    beds: 2,
    baths: 2,
    sqft: 110,
    image: 'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800&q=80',
    status: 'Disponible',
    description: 'Vista al mar desde el malecón de Manta. Edificio con ascensor y seguridad.',
  },
  {
    id: 'mock-8',
    title: 'Casa en zona patrimonial de Cuenca',
    price: 275_000,
    location: 'El Vergel, Cuenca',
    beds: 4,
    baths: 3,
    sqft: 260,
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80',
    status: 'En venta',
    description: 'Casa restaurada en barrio patrimonial de Cuenca. Patio interior y acabados de calidad.',
  },
] as const;
